### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jenningsanderson**
Updating the readme since now we know how to actually write markdown

@FLaskowski : What are you up to these days?

@bign8 @FLaskowski : creating this pull request to say hi; this was one of our first git repos.  How quaint.  What's new guys?  

keep in touch: jennings.anderson@gmail.com

### CODE REVIEW

**Comment by bign8** [comment]
Wow, Looking back on some of these old repos is humbling.  Great to hear from you @jenningsanderson !

**Comment by bign8** [comment]
Speaking of a blast from the past...

**Comment by jenningsanderson** [comment]
@bign8.  This. This is faaantastic.

@FLaskowski -- I hope you see this.

**Comment by FLaskowski** [comment]
Hey guys!  Long time no talk. Bizarrely I was scrolling through my old
facebook feed this morning and stumbled across the picture of us about 20
minutes before reading this email.

To answer your early question Jennings, I'm finishing up my PhD at the
University of Oregon. I've been doing research on a type of solar cell
which converts incident solar energy into hydrogen gas. If you're
interested, here's our most recent publication on the topic:
https://pubs.acs.org/doi/abs/10.1021/jacs.8b09449. With luck, I'll be
defending in July. Right now I'm agonizing over what do afterwards. My
favorite options are: (1) pursue a post-doc in battery sciences to improve
my knowledge and generally enjoy life, (2) find a job working for a
computer chip or solar cell manufacturer/developer to actually get payed
something halfway decent, (3) move to Japan and become a hiking hermit.

What about you two? How's all that programming going? You graduating soon
Jennings? Also haha @ "Updating the readme since *now we know how to
actually write markdown*" - speak for yourself. I've forgotten everything I
ever knew about programming.  =)

Best,
Forrest

**Comment by FLaskowski** [comment]
*Realized that the replyAll didn't quite workout in that last one. Try2:*

Hey guys!  Long time no talk. Bizarrely I was scrolling through my old
facebook feed this morning and stumbled across the picture of us about 20
minutes before reading this email.

To answer your early question Jennings, I'm finishing up my PhD at the
University of Oregon. I've been doing research on a type of solar cell
which converts incident solar energy into hydrogen gas. If you're
interested, here's our most recent publication on the topic:
https://pubs.acs.org/doi/abs/10.1021/jacs.8b09449. With luck, I'll be
defending in July. Right now I'm agonizing over what do afterwards. My
favorite options are: (1) pursue a post-doc in battery sciences to improve
my knowledge and generally enjoy life, (2) find a job working for a
computer chip or solar cell manufacturer/developer to actually get payed
something halfway decent, (3) move to Japan and become a hiking hermit.

What about you two? How's all that programming going? You graduating soon
Jennings? Also haha @ "Updating the readme since *now we know how to
actually write markdown*" - speak for yourself. I've forgotten everything I
ever knew about programming.  =)

Best,
Forrest

**Pull request merged**
